---
kind: pipeline
type: docker
name: build

trigger:
  event:
    - push

platform:
  os: linux
  arch: amd64

anchors:
  artifactory_credentials: &artifactory_credentials
    ARTIFACTORY_USER:
      from_secret: artifactory_user
    ARTIFACTORY_PASSWORD:
      from_secret: artifactory_password
  vault_tag: &vault_tag
    VAULT_VERSION: 
      from_secret: vault_version
  commands: &commands
    - apk add --no-cache curl
    - curl -sSL -o /usr/local/bin/vault.zip https://releases.hashicorp.com/vault/$(echo $VAULT_VERSION)/vault_$(echo $VAULT_VERSION)_linux_amd64.zip
    - unzip /usr/local/bin/vault.zip -d /usr/local/bin
    - chmod +x /usr/local/bin/vault
    - apk add --no-cache build-base sqlite-dev
    - bundle install --jobs=4 --retry=3
    - bundle exec rake app:db:create
    - bundle exec rake app:db:schema:load
    - bundle exec rake app:db:test:prepare
    - bundle exec rake


concurrency:
  limit: 1

steps:
  - name: build_ruby4
    image: quay.io/fundingcircle/alpine-ruby-builder:2.6
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_4.2.gemfile
      <<: [*vault_tag, *artifactory_credentials]
    commands: *commands

  - name: build_ruby5
    image: quay.io/fundingcircle/alpine-ruby-builder:2.6
    environment:
      RAILS_ENV: test
      BUNDLE_GEMFILE: gemfiles/rails_5.0.gemfile
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      <<: [*vault_tag, *artifactory_credentials]
    commands: *commands

  - name: build_ruby51
    image: quay.io/fundingcircle/alpine-ruby-builder:2.6
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_5.1.gemfile
      RAILS_ENV: test
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      <<: [*vault_tag, *artifactory_credentials]
    commands: *commands

  - name: build_ruby52
    image: quay.io/fundingcircle/alpine-ruby-builder:2.6
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_5.2.gemfile
      RAILS_ENV: test
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      <<: [*vault_tag, *artifactory_credentials]
    commands: *commands

  - name: build_ruby6
    image: quay.io/fundingcircle/alpine-ruby-builder:3.0
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_6.gemfile
      RAILS_ENV: test
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      <<: [*vault_tag, *artifactory_credentials]
    commands: *commands