language: ruby
cache: bundler
dist: trusty
sudo: false

gemfile:
  - Gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

before_install:
  - wget -O vault.zip -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault.zip
  - mkdir -p ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
  - bundle exec rake app:db:test:prepare
