version: 2
jobs:
  tests:
    docker:
      - image: ruby:2.4.4-alpine
        environment:
          RACK_ENV: test
          VAULT_VERSION: 0.6.0
    steps:
      - checkout
      - run: apk add --no-cache build-base sqlite-dev tzdata
      - run:
          name: Install Vault
          command: |
            wget -O vault.zip -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
            unzip vault.zip
            mv vault /usr/local/bin/
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - run: bundle exec rake app:db:create
      - run: bundle exec rake app:db:schema:load
      - run: bundle exec rake app:db:test:prepare
      - run: bundle exec rspec
  publish-pre-release:
    docker:
      - image: ruby:2.4.4-alpine
    steps:
      - checkout
      - run:
          name: Install cURL
          command: apk add --no-cache curl
      - run:
          name: Login to JFrog
          command:
            mkdir -p ~/.gem
            curl --user "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD" https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems/api/v1/api_key.yaml > ~/.gem/credentials
            chmod 600 ~/.gem/credentials
      - run:
          name: Install Gem Versioner
          command: gem install gem-versioner --version '~> 1.0' --no-document
      - run:
          name: Build gem
          command: |
            PRE_RELEASE="$CIRCLE_BRANCH" gem build "$CIRCLE_PROJECT_REPONAME".gemspec
      - run:
          name: Publish gem
          command: |
            package=$(ls -t1 "$CIRCLE_PROJECT_REPONAME"-*.gem | head -1)
            gem push "$package" --host https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems-pre-releases
workflows:
  version: 2
  test-then-publish:
    jobs:
      - tests
      - publish-pre-release:
          context: org-global
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
          requires:
            - tests
