version: 2
jobs:
  tests:
    docker:
      - image: ruby:2.4.4-alpine
        environment:
          RACK_ENV: test
          VAULT_VERSION: 0.10.0
    steps:
      - checkout
      - run: apk add --no-cache build-base sqlite-dev tzdata
      - run:
          name: Install Vault
          command: |
            wget -O vault.zip -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
            unzip vault.zip
            mv vault /usr/local/bin/
      - restore_cache:
          keys:
            - vault-rails-{{checksum "vault.gemspec" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: vault-rails-{{checksum "vault.gemspec" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake app:db:create
      - run: bundle exec rake app:db:schema:load
      - run: bundle exec rake app:db:test:prepare
      - run: bundle exec rspec

  publish-pre-release:
    docker:
      - image: ruby:2.4.4-alpine
    steps:
       - checkout
       - run:
           name: Install cURL
           command: apk add --no-cache curl
       - run:
           name: Login to JFrog
           command: |
             mkdir -p ~/.gem
             curl --user "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD" https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems/api/v1/api_key.yaml > ~/.gem/credentials
             chmod 600 ~/.gem/credentials
       - run:
           name: Install Gem Versioner
           command: gem install gem-versioner --version '~> 1.0' --no-document
       - run:
           name: Build gem
           command: |
             PRE_RELEASE="$CIRCLE_BRANCH" gem build vault.gemspec
       - run:
           name: Publish gem
           command: |
             package=$(ls -t1 vault-rails-*.gem | head -1)
             gem push "$package" --host https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems-pre-releases

  publish-release:
    docker:
      - image: ruby:2.4.4-alpine
    steps:
      - checkout
      - run:
          name: Install cURL
          command: apk add --no-cache curl
      - run:
          name: Login to JFrog
          command: |
            mkdir -p ~/.gem
            curl --user "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD" https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems/api/v1/api_key.yaml > ~/.gem/credentials
            chmod 600 ~/.gem/credentials
      - run:
          name: Install Gem Versioner
          command: gem install gem-versioner --version '~> 1.0' --no-document
      - run:
          name: Build gem
          command: |
            gem build vault.gemspec
      - run:
          name: Publish gem
          command: |
            package=$(ls -t1 vault-rails-*.gem | head -1)
            gem push "$package" --host https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems-local

workflows:
  version: 2

  test-and-release:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
      - publish-pre-release:
          context: org-global
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
          requires:
            - tests
      - publish-release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
          requires:
            - tests
