version: 2

aliases:
  environment: &environment
    RACK_ENV: test
    VAULT_VERSION: 0.10.4
  command: &ruby-command |
      bundle check --path=vendor/bundle || bundle install --binstubs --jobs 4 --path=vendor/bundle --retry 3
      bundle exec rake app:db:create
      bundle exec rake app:db:schema:load
      bundle exec rake app:db:test:prepare
      bundle exec rake
  cache:
    - restore_cache: &restore_cache
        keys:
          - vault-rails-{{checksum "fc-vault-rails.gemspec" }}-{{checksum "Appraisals" }}
    - save_cache:  &save_cache
          key: vault-rails-{{checksum "fc-vault-rails.gemspec" }}-{{checksum "Appraisals" }}
          paths:
            - vendor/bundle
  runs:
    - run: &install-vault
        name: Install Vault
        command: |
          wget -O vault.zip -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/
    - run: &rails4
        shell: /bin/bash -l
        name: Rails 4.2
        environment:
          BUNDLE_GEMFILE: gemfiles/rails_4.2.gemfile
        command: *ruby-command
    - run: &rails5
        shell: /bin/bash -l
        name: Rails 5.0
        environment:
          BUNDLE_GEMFILE: gemfiles/rails_5.0.gemfile
        command: *ruby-command
    - run: &rails51
        shell: /bin/bash -l
        name: Rails 5.1
        environment:
          BUNDLE_GEMFILE: gemfiles/rails_5.1.gemfile
        command: *ruby-command
    - run: &rails52
        shell: /bin/bash -l
        name: Rails 5.2
        environment:
          BUNDLE_GEMFILE: gemfiles/rails_5.2.gemfile
        command: *ruby-command
    - run: &rails6
        shell: /bin/bash -l
        name: Rails 6
        environment:
          BUNDLE_GEMFILE: gemfiles/rails_6.gemfile
        command: *ruby-command


jobs:
  test_ruby_2_4:
    docker:
      - image: circleci/ruby:2.4
        environment:
          <<: *environment
    steps:
      - checkout
      - run: *install-vault
      - run: *rails4
      - run: *rails5
      - run: *rails51
      - run: *rails52

  test_ruby_2_5:
    docker:
      - image: circleci/ruby:2.5
        environment:
          <<: *environment
    steps:
      - checkout
      - run: *install-vault
      - run: *rails4
      - run: *rails5
      - run: *rails51
      - run: *rails52
      - run: *rails6

  test_ruby_2_6:
    docker:
      - image: circleci/ruby:2.6
        environment:
          <<: *environment
    steps:
      - checkout
      - run: *install-vault
      - run: *rails5
      - run: *rails51
      - run: *rails52
      - run: *rails6

  test_ruby_2_7:
    docker:
      - image: circleci/ruby:2.7
        environment:
          <<: *environment
    steps:
      - checkout
      - run: *install-vault
      - run: *rails5
      - run: *rails51
      - run: *rails52
      - run: *rails6

  publish-pre-release:
    docker:
      - image: circleci/ruby:2.7
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: Login to JFrog
          command: |
            mkdir -p ~/.gem
            curl --user "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD" https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems/api/v1/api_key.yaml > ~/.gem/credentials
            chmod 600 ~/.gem/credentials

      - run:
          name: Install Gem Versioner
          shell: /bin/bash -l
          command: gem install gem-versioner --version '~> 1.0' --no-document

      - run:
          name: Build gem
          shell: /bin/bash -l
          command: |
            PRE_RELEASE="$CIRCLE_BRANCH" gem build fc-vault-rails.gemspec

      - run:
          name: Publish gem
          shell: /bin/bash -l
          command: |
            package=$(ls -t1 fc-vault-rails-*.gem | head -1)
            gem push "$package" --host https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems-pre-releases

  publish-release:
    docker:
      - image: circleci/ruby:2.7
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: Login to JFrog
          command: |
            mkdir -p ~/.gem
            curl --user "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD" https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems/api/v1/api_key.yaml > ~/.gem/credentials
            chmod 600 ~/.gem/credentials

      - run:
          name: Install Gem Versioner
          shell: /bin/bash -l
          command: gem install gem-versioner --version '~> 1.0' --no-document

      - run:
          name: Build gem
          shell: /bin/bash -l
          command: |
            gem build fc-vault-rails.gemspec

      - run:
          name: Publish gem
          shell: /bin/bash -l
          command: |
            package=$(ls -t1 fc-vault-rails-*.gem | head -1)
            gem push "$package" --host https://fundingcircle.jfrog.io/fundingcircle/api/gems/rubygems-local

workflows:
  version: 2

  test-and-release:
    jobs:
      - test_ruby_2_4:
          context: org-global
          filters:
            tags:
              only: /.*/

      - test_ruby_2_5:
          context: org-global
          filters:
            tags:
              only: /.*/

      - test_ruby_2_6:
          context: org-global
          filters:
            tags:
              only: /.*/

      - test_ruby_2_7:
          context: org-global
          filters:
            tags:
              only: /.*/

      - publish-pre-release:
          context: org-global
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
          requires:
            - test_ruby_2_4
            - test_ruby_2_5
            - test_ruby_2_6
            - test_ruby_2_7

      - publish-release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
          requires:
            - test_ruby_2_4
            - test_ruby_2_5
            - test_ruby_2_6
            - test_ruby_2_7
